### ISSUE TITLE
Could we autodetect that .env.local has been created and hot-reload the whole app to suit?

### ISSUE THREAD

**Issue by Zorlin** [riffcc/orbiter#1]
Title pretty much describes the issue :)

**Comment by julienmalard** [comment]
Sorry; just saw this! I think this is actually already the case when running with vite in dev mode.
Did you mean on the production server as well?

**Comment by Zorlin** [comment]
Oh, if it's already the case in dev mode that might be good enough for now. Ideally prod should also do so, but it's not hugely necessary. Thanks!
