### ISSUE TITLE
Drop the background colour/border box/separation between content items

### ISSUE THREAD

**Issue by Zorlin** [riffcc/orbiter#38]
We want this to look seamless and the boxes gotta go ;)

Please go from this:

![telegram-cloud-photo-size-5-6339010419523440797-y](https://github.com/user-attachments/assets/af80fc1f-6a62-4765-a44c-5786e3322b4c)

to this

![telegram-cloud-photo-size-5-6339010419523440798-y](https://github.com/user-attachments/assets/bb597a92-8a36-44cd-8c5b-2541b43a2151)

**Comment by Sphirye** [comment]
Fixed in https://github.com/riffcc/orbiter/pull/40
