### ISSUE TITLE
Video starts playing outside viewport

### ISSUE THREAD

**Issue by goetzk** [riffcc/orbiter#39]
**Describe the bug**

When i load video https://orbiter.riff.cc/#/release/video/QmTWWUmvC9txvE7aHs9xHd541qLx3ax58urvx3Kb3SFK2Q (RiP Remix) (using Chrome on android) it starts but is off the top of the screen. i have to scroll up on the page to see the video.

**To Reproduce**

1. Go to https://orbiter.riff.cc/#/
2. Click on RiP!: A Remix Manifesto
3. The video is started, off the top of the viewport.

**Expected behavior**
Video starts in a visible part of the screen.

**Screenshots**

When the page loads
![Screenshot_2024-10-04-14-25-41-90_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/092c2257-eaf3-4781-995e-01d66c1ea938)

Expected
![Screenshot_2024-10-04-14-25-47-76_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/61946225-c07b-4323-a024-cf15490342bc)

**Additional context**

Chrome 129.0.668.81
OS Android 13; CPH2333 Build/TP1A (Oppo)

**Comment by Sphirye** [comment]
The scroll is persisting it position when moving between pages

I just pushed a fix in https://github.com/riffcc/orbiter/pull/41
